### ISSUE TITLE
Are there CSV versions of the feature vectors?

### ISSUE THREAD

**Issue by sgbaird** [lantunes/skipatom#6]
E.g. similar to https://github.com/anthony-wang/CrabNet/blob/master/data/element_properties/mat2vec.csv

https://github.com/anthony-wang/CrabNet/issues/29

**Comment by lantunes** [comment]
I have updated the project with a CSV file containing the learned vectors. The file is in the `data` folder, and is called `skipatom_20201009_induced.csv`: https://github.com/lantunes/skipatom/blob/main/data/skipatom_20201009_induced.csv.

**Comment by lantunes** [comment]
@sgbaird FYI, I've updated the CSV file, located at https://github.com/lantunes/skipatom/blob/main/data/skipatom_20201009_induced.csv, to fix a problem introduced when I created the file initially. You may want to update your version of this file.

**Comment by sgbaird** [comment]
@lantunes thanks! Got that added
